import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { McpAgent } from "agents/mcp";
import { z } from "zod";

const ATLAS_BASE = "https://api.atlascloud.ai";

// Extends the global `Env` (generated by `wrangler types` from wrangler.jsonc's
// Durable Object binding) with the two secrets set via `wrangler secret put`,
// which aren't declared in wrangler.jsonc so don't appear there automatically.
interface AtlasEnv extends Env {
	ATLASCLOUD_API_KEY: string;
	PROXY_AUTH_TOKEN: string;
}

async function atlasFetch(env: AtlasEnv, path: string, init: RequestInit = {}) {
	const res = await fetch(`${ATLAS_BASE}${path}`, {
		...init,
		headers: {
			Authorization: `Bearer ${env.ATLASCLOUD_API_KEY}`,
			"Content-Type": "application/json",
			...(init.headers || {}),
		},
	});
	const text = await res.text();
	return { status: res.status, body: text };
}

function textResult(body: string) {
	return { content: [{ type: "text" as const, text: body }] };
}

// Cloudflare Workers Durable Object bindings require the class name to match
// wrangler.jsonc's durable_objects.bindings[].class_name ("MyMCP") -- do not
// rename this class without updating wrangler.jsonc to match.
export class MyMCP extends McpAgent<AtlasEnv> {
	server = new McpServer({
		name: "atlascloud-proxy",
		version: "1.0.0",
	});

	async init() {
		this.server.registerTool(
			"atlas_get_balance",
			{ inputSchema: {} },
			async () => {
				const { body } = await atlasFetch(this.env, "/public/v1/balance");
				return textResult(body);
			},
		);

		this.server.registerTool(
			"atlas_list_models",
			{ inputSchema: { type: z.enum(["Text", "Image", "Video", "Audio"]).optional() } },
			async ({ type }) => {
				// atlas_list_models has no documented REST filter endpoint of its own;
				// atlas_search_docs is the closest read-only catalog search available.
				const q = type ? `?query=${encodeURIComponent(type)}` : "";
				const { body } = await atlasFetch(this.env, `/api/v1/model/search${q}`);
				return textResult(body);
			},
		);

		this.server.registerTool(
			"atlas_get_prediction",
			{ inputSchema: { prediction_id: z.string() } },
			async ({ prediction_id }) => {
				const { body } = await atlasFetch(
					this.env,
					`/api/v1/model/prediction/${encodeURIComponent(prediction_id)}`,
				);
				return textResult(body);
			},
		);

		this.server.registerTool(
			"atlas_generate_image",
			{ inputSchema: { model: z.string(), params: z.record(z.string(), z.unknown()) } },
			async ({ model, params }) => {
				const { body } = await atlasFetch(this.env, "/api/v1/model/generateImage", {
					method: "POST",
					body: JSON.stringify({ model, ...params }),
				});
				return textResult(body);
			},
		);

		this.server.registerTool(
			"atlas_generate_video",
			{ inputSchema: { model: z.string(), params: z.record(z.string(), z.unknown()) } },
			async ({ model, params }) => {
				const { body } = await atlasFetch(this.env, "/api/v1/model/generateVideo", {
					method: "POST",
					body: JSON.stringify({ model, ...params }),
				});
				return textResult(body);
			},
		);

		this.server.registerTool(
			"atlas_generate_audio",
			{ inputSchema: { model: z.string(), params: z.record(z.string(), z.unknown()) } },
			async ({ model, params }) => {
				const { body } = await atlasFetch(this.env, "/api/v1/model/generateAudio", {
					method: "POST",
					body: JSON.stringify({ model, ...params }),
				});
				return textResult(body);
			},
		);

		this.server.registerTool(
			"atlas_get_model_costs",
			{ inputSchema: { start_date: z.string(), end_date: z.string() } },
			async ({ start_date, end_date }) => {
				const { body } = await atlasFetch(
					this.env,
					`/api/v1/model/costs?start_date=${encodeURIComponent(start_date)}&end_date=${encodeURIComponent(end_date)}`,
				);
				return textResult(body);
			},
		);
	}
}

export default {
	fetch(request: Request, env: AtlasEnv, ctx: ExecutionContext) {
		const url = new URL(request.url);

		// Auth: the deploy-specific secret token must be the last path segment,
		// e.g. https://<worker>.workers.dev/mcp/<PROXY_AUTH_TOKEN>. Cowork's
		// "Add custom connector" form has no generic auth-header field (only
		// OAuth, which is a much bigger lift for a single-user proxy), so the
		// token lives in the URL itself -- keep this URL secret, treat it like
		// a password. Without a correct match, every request is rejected before
		// ATLASCLOUD_API_KEY is ever touched.
		const match = url.pathname.match(/^\/mcp\/([^/]+)$/);
		if (!match || !env.PROXY_AUTH_TOKEN || match[1] !== env.PROXY_AUTH_TOKEN) {
			return new Response("Not found", { status: 404 });
		}

		// Rewrite to a clean "/mcp" before delegating -- don't rely on
		// McpAgent.serve() to tolerate the extra token path segment itself.
		const rewrittenUrl = new URL(url);
		rewrittenUrl.pathname = "/mcp";
		const rewrittenRequest = new Request(rewrittenUrl, request);

		return MyMCP.serve("/mcp").fetch(rewrittenRequest, env, ctx);
	},
};
